fix bug
➜  sandworms git:(master) ✗ grunt jshint
Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: /Users/fox/Documents/biddecor/sandworms/Gruntfile.js:7
>>   },
>>    ^
>> Unexpected token ,
Warning: Task "jshint" not found. Use --force to continue.

Aborted due to warnings.