fix bug
➜  sandworms git:(master) grunt sprite
Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: /Users/fox/Documents/biddecor/sandworms/Gruntfile.js:8
>>     uglify: {
>>     ^^^^^^
>> Unexpected identifier
Warning: Task "sprite" not found. Use --force to continue.

Aborted due to warnings.